config/routes.rb
Resala::Application.routes.draw do  
  resources :sessions, :only => [:new]
  resources :testimonials, :branches, :only => [:index, :show]
  resources :newsletter_subscribers, :only => [:create]
  resources :donation_requests, :feedbacks, :only => [:new, :create]
  resources :pages, :only => [:show, :user_info]
  resources :questions, :only => :index
  resources :activity_categories, :only => [:index,:show] do
    resources :questions, :only => :index
  end
  resources :activities, :only => [:show, :new, :create, :index]  do
    resources :achievements, :only => [:new, :create] 
    member do
      post :notify_comment
      get :join_activity
      post :quit
      get :volunteers
    end
  end
  resources :donations, :only=>[:new,:create,:index] do
    collection do
      get :handle_response
    end 
  end
  resources :news, :stories, :only => [:index, :show]  do
    collection do
      get 'search'
    end
  end
  resources :volunteers, :only => [:new, :create, :index, :show, :edit, :update] do 
    collection do
      post 'activities_authority'
      get 'request_activities_authority'
      get 'gateway'
    end
    member do
      get 'activities'
      get 'dashboard'
      get 'previous_activities'
      get 'upcoming_activities'
      get 'volunteer_details'
      post 'update_join_activity'
    end
    resources :activities, :only => []  do
      resources :achievements, :only => [:new, :create, :show] 
      member do
        get :volunteers
    	post :request_close
      	get :preview
      end
    end
  end
  
  namespace :admin do
    resources :activity_categories, :branches, :testimonials, :articles, :newsletter_subscribers, :achievements_types
    resources :donation_requests, :only => [:index, :show, :destroy, :update]
    resources :donations, :only => [:index]
    resources :activities, :only => [:index,:show,:update] do
      member do
        put 'publish'
        put 'announce'
        put 'reject'
        get 'members'
        put 'close'
      end
      collection do
        get 'email_counts'
      end
    end
    resources :volunteers, :only => [:index, :show, :edit, :update, :destroy] do 
      member do
        get 'authority_volunteer_details'
        post 'update_activities_authority_status'
      end
    end
    resources :admins, :only => [:index] do 
      member do
        post 'activate'
      end
    end
    resources :reports, :only=>[] do
      collection do
        get 'volunteers'
        get 'donations'
        get 'donation_requests'
      end
    end
    resources :questions, :except => [:show]
    match '/broadcast_email' => 'emails#new',    :as=>'new_bulk_email' , :via => :get
    match '/broadcast_email' => 'emails#create', :as=>'send_bulk_email', :via => :post
    match '/email_counts' => 'emails#email_counts', :as=>'email_counts', :via => :post
    match '/broadcast_email/preview' => 'emails#preview', :as=>'email_preview', :via=> :post
    match '/activity_categories/update_order/:id/:prev_id' => 'activity_categories#update_order', :as => :update_order, :via => :post
  end
  
  get "media/index"
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/admin_login/:provider' => 'sessions#admin_login', :as => :admin_login
  match '/login/:provider' => 'sessions#login', :as => :login
  match '/volunteering/:provider' => 'sessions#volunteering', :as => :volunteering
  match '/media(/:media_type)(/pages/:page)(.:format)' => 'media#index', :as=> 'media'
  match '/media/albums/:album_id/:media_type(/pages/:page)(.:format)' => 'media#index', :as=> 'album_photos'
  match '/media/:media_type/:fb_id(.:format)' => 'media#show', :as=> 'media_show'
  match '/admin' => 'admin/articles#index'
  match 'home' => 'pages#show', :id => :home
  match 'user_info' => 'pages#user_info'
  match '/volunteers/:id/activities/:activity_id' => 'volunteers#activity', :via => :get, :as=> 'volunteer_activity'
  match '/volunteers/:id/activities/:activity_id/edit' => 'activities#edit', :as=> 'edit_volunteer_activity'
  match '/volunteers/:id/activities/:activity_id' => 'activities#update', :via => :put, :as=> 'update_volunteer_activity'
  match '/subscribe_confirmation/:token' => 'newsletter_subscribers#subscribe_confirmation', :as=> 'subscribe_confirmation'
  match '/unsubscribe' => 'newsletter_subscribers#unsubscribe', :as=> 'unsubscribe'
  match '/unsubscribe_confirmation/:token' => 'newsletter_subscribers#unsubscribe_confirmation', :as=> 'unsubscribe_confirmation'
  match '/Adm!nD@ta$3cuReP@ge' => 'pages#admin_data_entry', :via=> :get, :as=> 'admin_data_entry'
  match '/update_admin_data' => 'pages#update_admin_data', :via=> :put
  root :to => 'pages#show', :id => :home
  

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  before_destroy :before_destroy_method
  validates :name, :presence=>true, :uniqueness=>true, :length=>{:maximum=>250}
  validates :description,:length=>{:maximum=>2000}
  validates :city, :presence=>true
  validates :address, :presence=>true
  validates :email, :format=>{:with => /^[A-Za-z0-9._]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/ , :unless => Proc.new{|e| e.email.blank?} }
  validates :phones, :length=>{:maximum=>100, :minimum=>7, :allow_blank=>true}, :format=>{:with => /^[0-9\s\-]+$/ , :unless => Proc.new{|b| b.phones.blank?} }
  
  belongs_to :city
  has_and_belongs_to_many :activity_categories
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :media, :class_name=> 'Media'
  has_and_belongs_to_many :activities
  has_many :volunteers
  
  accepts_nested_attributes_for :activity_categories, :reject_if => proc{|attrs| attrs.all? {|k, v| v.blank?}}
  
  scope :latest, order("created_at desc")
  
  attr_accessor :alternative_branch
  
  def self.branches_list
    Branch.order("city_id").collect{|b| ["#{b.city.name} - #{b.name}", b.id]}
  end
  
  def before_destroy_method
    # volunteers
    self.volunteers.update_all(:branch_id => self.alternative_branch.id )
    # activities
    self.activities.each{ |ac| 
      ac.branches << self.alternative_branch if !ac.branches.include? self.alternative_branch 
    }
    # related articles
    self.articles.each{|ar|
      ar.branches << self.alternative_branch if !ar.branches.include? self.alternative_branch
    }
  end
end

app/controllers/admin/branches_controller.rb
class Admin::BranchesController < Admin::AdminController
  before_filter :prepare_lists, :only => [:new, :edit, :create, :update]
  before_filter :handle_media_list, :only=>[:create,:update]
  # cache_sweeper :branch_sweeper, :only=>[:create, :update, :destroy]
  
  def index
    @branches = Branch.all
  end
  
  def new
    @branch = Branch.new
  end
  
  def show
    @branch = Branch.find(params[:id])
  end
  
  def edit
    @branch = Branch.find(params[:id])
    @lat = @branch.latitude 
    @lng = @branch.longitude
    @marked = (@lat && @lng)
  end
  
  def update
    @branch = Branch.find(params[:id])
    update_activities
    if @branch.update_attributes(params[:branch])
      redirect_to(admin_branches_path, :notice => t("messages.saved", :name => t("branch.branch")))
    else
      render :action => "edit"
    end
  end
  
  def create
    @branch = Branch.new(params[:branch])
    update_activities
    if @branch.save
      redirect_to(admin_branches_path, :notice => t("messages.saved", :name => t("branch.branch")))
    else
      render :action => "new"
    end
  end
  
  def destroy
    if params[:branch][:alternative_branch] == ""
      redirect_to admin_branches_url, :alert => t("messages.select_alternate_branch")
    else
      @branch = Branch.find(params[:id])
      @branch.alternative_branch = Branch.where(:id => params[:branch][:alternative_branch]).first
      authorize! :destroy, @branch
      if @branch.destroy
        redirect_to admin_branches_url , :notice => t("messages.deleted")
      else
        redirect_to admin_branches_url , :alert => t("messages.branch_deletion_failed")
      end
    end
  end

  #######
  private
  #######
  
  def handle_media_list
    begin
      if(params[:branch][:media])
        media_list = ActiveSupport::JSON.decode(params[:branch][:media])
        media_list = media_list.collect{|m| Media.find_or_create(m['id'] , m['mediaType'], m['thumbnail'])}
        params[:branch][:media] = media_list
      end
    rescue
    end
  end
  
  def update_activities
    activity_categories = []
    
    params[:activity_categories].each do |activity_category_id|
      activity_category = ActivityCategory.where(:id=>activity_category_id).first
      activity_categories << activity_category if activity_category 
    end unless params[:activity_categories].blank?
    
    @branch.activity_categories = activity_categories
  end
  
  def prepare_lists
    @cities_for_select = City.all
    @activity_categories = ActivityCategory.all
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  # caches_action :show, :layout=>true, :expires_in=>CACHE_EXPIRES_IN.call
  # caches_action :index, :layout=>true, :cache_path => :cache_path.to_proc, :expires_in=>CACHE_EXPIRES_IN.call
  
  def show
    @branch = Branch.find params[:id]
    @branch_activity_categories = @branch.activity_categories
    @query = Media.construct_query(:media_type=>'photos',:owner_id=>@branch.id,:owner_type=>'branch',:page=>1)
    
    respond_to do |format|
      format.html{ redirect_to branches_path(:branch_id=>@branch.id) }
      format.js { render :status => :ok }
    end
  end
  
  def index
    # if params[:city_id]
    #   @city_branches = City.find(params[:city_id]).branches.order("name")
    #   @select_tag_name = "volunteer[branch_id]"
    # else
    @branches = Branch.order("city_id asc")
    @cities = City.order("name asc")
    @city_branches = Branch.branches_list
    # end
    
    unless params[:branch_id].blank?
      @branch = Branch.find(params[:branch_id])
      @branch_activity_categories = @branch.activity_categories
      @query = Media.construct_query(:media_type=>'photos',:owner_id=>@branch.id,:owner_type=>'branch',:page=>1)
    else 
      @branch = Branch.new
    end
    
    respond_to do |format|
      format.html
      format.js { render :status => :ok }
    end
  end
  
  # def cache_path
  #   {:city_id => (params[:city_id] || 0)}
  # end
end

app/helpers/admin/branches_helper.rb
module Admin::BranchesHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
  def info_summary(branch)
    %Q(
      <div>
        <h3>#{branch.name}</h3>
        <p><a href='javascript: showBranchData("#{branch.id}");' >#{t("messages.more_branches")}</a></p>
      </div>
    ).html_safe
  end
end

app/views/branches/_show.html.erb
<div class="branch_details_top">
  <div class="branch_title">                
    <h2><%= branch.name %></h2>
  </div>
  <div class="branchDescreption">
    <p><%= branch.description.html_safe unless branch.description.blank? %></p>
    <% if branch_activity_categories.size > 0 %>
      <h3>أنشطة متعلقة بالفرع : </h3>
      <p>
        <% branch_activity_categories.each do |activity_category|%>
          <span><%= link_to activity_category.name, activity_category %></span>
        <% end %>
      </p>                 
    <% end %>
    <ul class="branch_contact">
      <% unless @branch.phones.blank? %>
        <li><label class="hideText contact_tel">تليفونات</label> <span><%= @branch.phones %></span></li>
      <% end %>
      <% unless @branch.email.blank? %>
      <li><label class="hideText contact_email">البريد الإلكتروني</label><strong><%= @branch.email %></strong></li>
      <% end %>
      <li><label class="hideText contact_add">العنوان</label><span><%= @branch.address %></span></li>                                                      
    </ul>
  </div>
</div>
<div class="branch_details_footer"></div>

app/views/branches/index.html.erb
<% @title = "فروع  رسالة"; @title_class = 'branch_title' ;@section_title = @title %>
<% content_for :custom_section_header_content do %>
فروع رسالة مقسمة حسب المحافظات، وأهم أخبار وأنشطة كل منها.
<% end %>


<div class="branches">
  <div class="section_intro">
    <p>
      لعرض فروع احد المدن، يرجى اختبار المدينة عن طريق نقرها على الخريطة‫.
    </p>
  </div>
  <div class="mapBox" id="map_canvas" style="width: 500px; height: 500px; display: none;"></div>
  
  <div class="filtering">
    <%= form_tag branches_path, :method => 'get' do |f| %>
      <fieldset>
        <div class="form_filed">
          <label>اختر الفرع</label> 
          <style>.select_wrap .mandatory: display: none;</style>                          
          <div class="select_wrap">
            <div id="select_field_branch_id" class="select_field">                            
              <%= select_tag :branch_id, options_for_select([["أختر الفرع", ""]]) + options_for_select(@city_branches, @branch.id) %>
            </div>
          </div>
        </div>
        <div>
        </div>
      </fieldset>
    <% end %>
  </div>
  <div id="branch_show_container" style="<%= 'display: none;' if @branch.id.blank? %>" >
    <% unless @branch.id.blank? %>
    <%= render :partial => "show", :locals=>{:branch => @branch, :branch_activity_categories=>@branch_activity_categories, :query=>@query} %>
    <% end %>
  </div>
  <div id="branch_show_media_container" style="<%= 'display: none;' if @branch.id.blank? %>" >
    <% unless @branch.id.blank? %>
    <%= render :partial=> 'media/index' ,:locals=>{:media_type=> 'photos', :query=>@query, :owner_type=> 'branch', :owner_id=> @branch.id, :page=>1,  :per_page=> Media::PER_PAGE}  %>
    <% end %>
  </div>
</div>
  
<% content_for :javascripts do %>
  <%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false&language=ar", "map", "cust_select_plugin", "branches" %>
  <script>
    initialize_map("", "");
    $("#map_canvas").show();
    <% @branches.each do |branch| %>
      <% if branch.longitude && branch.latitude %>
        addMarker("<%= branch.longitude %>", "<%= branch.latitude %>", "<%= escape_javascript (info_summary(branch)) %>", "pointer.png");
      <% end %>
    <% end %>
    <% unless @branch.id.blank? %>
      <% if @branch.longitude && @branch.latitude %>
        if(map){
          loc = new google.maps.LatLng(<%= @branch.latitude %>, <%= @branch.longitude %>);
          map.setCenter(loc);
          map.setZoom(16);
        }
      <% end %>
    <% end %>
  </script>
<% end %>

app/views/branches/index.js.erb
<% if @city_branches %>
  $("#select_field_branch_id").html("<%= escape_javascript(select_tag(:branch_id, options_for_select([["أختر الفرع", ""]]) + options_from_collection_for_select(@city_branches, "id", "name", 0), :name=>@select_tag_name ? @select_tag_name : "branch_id", :class=>"text") + (" <span class='mandatory'> *</span> ").html_safe) %>");
<% end %>

app/views/branches/show.js.erb
$('#branch_show_container').hide();
$('#branch_show_container').html("<%= escape_javascript(render :partial => "show", :locals=>{:branch => @branch, :branch_activity_categories=>@branch_activity_categories, :query=>@query}) %>").show("slow");

$('#branch_show_media_container').hide();
$('#branch_show_media_container').html("<%= escape_javascript(render :partial=> 'media/index' ,:locals=>{:media_type=> 'photos', :query=>@query, :owner_type=> 'branch', :owner_id=> @branch.id, :page=>1,  :per_page=> Media::PER_PAGE}) %>").show("slow");

window.location = "#branch_show_container";

<% if @branch.longitude && @branch.latitude %>
if(map){
  loc = new google.maps.LatLng(<%= @branch.latitude %>, <%= @branch.longitude %>);
  map.setCenter(loc);
  map.setZoom(16);
}
<% end %>

<% media_type ='photos' %>
<% query = @query %>
<% owner_type = 'branch' %>
<% owner_id = @branch.id %>
<% page = 1 %>
<% per_page = Media::PER_PAGE %>

$(document).ready(function()  {
  var tbs = $( ".tabs" ).tabs();
  var tabIndex = <%= media_type == 'videos' ? 1 : 0 %>;
  tbs.tabs('select', tabIndex);
  var query = "<%= query %>";
  months = <%= js_months %>;
  getData(query,
          function(response){
            <% if media_type =='photos' && owner_id.nil? %>
            $('#photos-header').show();
            <% elsif (media_type == 'albums' || 'videos') || owner_id %>
            $('#photos-header').hide();
            $('.album-link').live('click', function(){
              $('#album_name').html(this.name);
            });
            <% else %>
            $('#album_name').html("");
            $('#photos-header').show();
            <% end %>
            if(response.error_code){
              //alert(response.error_msg)
            }else{
              renderResponse(response,{
                               template : "#<%= media_type %>-list-template",
                               container: "#<%= media_type %>-list",
                               <% if !local_assigns[:no_pagination] %>
                               paginated: true,
                               next:'<%= params[:album_id] ? album_photos_path(params[:album_id],media_type, page + 1,:no_pagination=>local_assigns[:no_pagination],:per_page => per_page, :format=>'js') : media_path(media_type, page + 1, :format=>'js' ,:no_pagination=>local_assigns[:no_pagination],:per_page => per_page ,:owner_id=> owner_id, :owner_type=> owner_type ) %>',
                               prev:<%= page == 1 ? 'undefined' : ("'" + (params[:album_id] ? album_photos_path(params[:album_id],media_type, page - 1 ,:no_pagination=>local_assigns[:no_pagination],:per_page => per_page ,:format=>'js') : media_path(media_type, page - 1, :format=>'js',:no_pagination=>local_assigns[:no_pagination],:per_page => per_page ,:owner_id=> owner_id, :owner_type=> owner_type)) + "'") %>,
                               pagContainer: "#<%= media_type %>-pag",
                               <% end %>
                               perPage: <%= per_page %>
                             });
            <% if media_type == 'photos' || 'videos' %>
              trigger_fancybox();
            <% end %>
            }
          });
  $("#videos-tab-link").click(function(){
    $("#photos-list").html("");
    $("#albums-list").html("");
    $.ajax('<%= media_path('videos',:format=>'js',:no_pagination=>local_assigns[:no_pagination],:per_page => per_page,:owner_id=> owner_id, :owner_type=> owner_type) %>');
  });
  $("#photos-tab-link").click(function(){
    $("#videos-list").html("");
    <% if owner_id %>
      $.ajax('<%= media_path('photos',:format=>'js',:no_pagination=>local_assigns[:no_pagination],:per_page => per_page,:owner_id=> owner_id, :owner_type=> owner_type) %>');
    <% else %>
      $.ajax('<%= media_path('albums',:format=>'js',:no_pagination=>local_assigns[:no_pagination],:per_page => per_page) %>');
    <% end %>
  });
});