config/routes.rb
Resala::Application.routes.draw do  
  resources :sessions, :only => [:new]
  resources :testimonials, :branches, :only => [:index, :show]
  resources :newsletter_subscribers, :only => [:create]
  resources :donation_requests, :feedbacks, :only => [:new, :create]
  resources :pages, :only => [:show, :user_info]
  resources :questions, :only => :index
  resources :activity_categories, :only => [:index,:show] do
    resources :questions, :only => :index
  end
  resources :activities, :only => [:show, :new, :create, :index]  do
    resources :achievements, :only => [:new, :create] 
    member do
      post :notify_comment
      get :join_activity
      post :quit
      get :volunteers
    end
  end
  resources :donations, :only=>[:new,:create,:index] do
    collection do
      get :handle_response
    end 
  end
  resources :news, :stories, :only => [:index, :show]  do
    collection do
      get 'search'
    end
  end
  resources :volunteers, :only => [:new, :create, :index, :show, :edit, :update] do 
    collection do
      post 'activities_authority'
      get 'request_activities_authority'
      get 'gateway'
    end
    member do
      get 'activities'
      get 'dashboard'
      get 'previous_activities'
      get 'upcoming_activities'
      get 'volunteer_details'
      post 'update_join_activity'
    end
    resources :activities, :only => []  do
      resources :achievements, :only => [:new, :create, :show] 
      member do
        get :volunteers
    	post :request_close
      	get :preview
      end
    end
  end
  
  namespace :admin do
    resources :activity_categories, :branches, :testimonials, :articles, :newsletter_subscribers, :achievements_types
    resources :donation_requests, :only => [:index, :show, :destroy, :update]
    resources :donations, :only => [:index]
    resources :activities, :only => [:index,:show,:update] do
      member do
        put 'publish'
        put 'announce'
        put 'reject'
        get 'members'
        put 'close'
      end
      collection do
        get 'email_counts'
      end
    end
    resources :volunteers, :only => [:index, :show, :edit, :update, :destroy] do 
      member do
        get 'authority_volunteer_details'
        post 'update_activities_authority_status'
      end
    end
    resources :admins, :only => [:index] do 
      member do
        post 'activate'
      end
    end
    resources :reports, :only=>[] do
      collection do
        get 'volunteers'
        get 'donations'
        get 'donation_requests'
      end
    end
    resources :questions, :except => [:show]
    match '/broadcast_email' => 'emails#new',    :as=>'new_bulk_email' , :via => :get
    match '/broadcast_email' => 'emails#create', :as=>'send_bulk_email', :via => :post
    match '/email_counts' => 'emails#email_counts', :as=>'email_counts', :via => :post
    match '/broadcast_email/preview' => 'emails#preview', :as=>'email_preview', :via=> :post
    match '/activity_categories/update_order/:id/:prev_id' => 'activity_categories#update_order', :as => :update_order, :via => :post
  end
  
  get "media/index"
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/admin_login/:provider' => 'sessions#admin_login', :as => :admin_login
  match '/login/:provider' => 'sessions#login', :as => :login
  match '/volunteering/:provider' => 'sessions#volunteering', :as => :volunteering
  match '/media(/:media_type)(/pages/:page)(.:format)' => 'media#index', :as=> 'media'
  match '/media/albums/:album_id/:media_type(/pages/:page)(.:format)' => 'media#index', :as=> 'album_photos'
  match '/media/:media_type/:fb_id(.:format)' => 'media#show', :as=> 'media_show'
  match '/admin' => 'admin/articles#index'
  match 'home' => 'pages#show', :id => :home
  match 'user_info' => 'pages#user_info'
  match '/volunteers/:id/activities/:activity_id' => 'volunteers#activity', :via => :get, :as=> 'volunteer_activity'
  match '/volunteers/:id/activities/:activity_id/edit' => 'activities#edit', :as=> 'edit_volunteer_activity'
  match '/volunteers/:id/activities/:activity_id' => 'activities#update', :via => :put, :as=> 'update_volunteer_activity'
  match '/subscribe_confirmation/:token' => 'newsletter_subscribers#subscribe_confirmation', :as=> 'subscribe_confirmation'
  match '/unsubscribe' => 'newsletter_subscribers#unsubscribe', :as=> 'unsubscribe'
  match '/unsubscribe_confirmation/:token' => 'newsletter_subscribers#unsubscribe_confirmation', :as=> 'unsubscribe_confirmation'
  match '/Adm!nD@ta$3cuReP@ge' => 'pages#admin_data_entry', :via=> :get, :as=> 'admin_data_entry'
  match '/update_admin_data' => 'pages#update_admin_data', :via=> :put
  root :to => 'pages#show', :id => :home
  

end

app/models/activity_category.rb
class ActivityCategory < ActiveRecord::Base
  validates :name, :presence=>true, :uniqueness=>true, :length=>{:maximum=>250}
  acts_as_list
  validates :front_photo_id, :presence=>true
  validates :short_description,:presence=>true, :length=>{:maximum=>600}
  has_and_belongs_to_many :branches
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :volunteers
  has_and_belongs_to_many :media, :class_name=> 'Media'
  has_and_belongs_to_many :activities
  has_and_belongs_to_many :donation_requests
  has_many :donations
  has_many :questions
  belongs_to :front_photo, :class_name => "Media"
  scope :latest, order("position ASC")
  scope :donatable, where(:donatable => true)
  default_scope order("position ASC")
  
  def front_photo_fb_id
    (photo = self.front_photo) ? photo.fb_id : nil
  end
  
  def front_photo_fb_id= fb_id
    self.front_photo = Media.find_by_fb_id fb_id
  end
end

app/controllers/activity_categories_controller.rb
class ActivityCategoriesController < ApplicationController
  caches_action :show, :layout=>true, :expires_in=>CACHE_EXPIRES_IN.call, :if => Proc.new{|x| params[:legacy].blank? }
  
  def index
    redirect_to ActivityCategory.latest.first
  end
  
  def show
    unless params[:legacy].blank?
      @activity_category = ActivityCategory.find_by_legacy_id(params[:id])
      redirect_to @activity_category if @activity_category
    end
    @activity_category ||= ActivityCategory.find(params[:id])
    @activity_categories = ActivityCategory.latest
    @news = @activity_category.articles.latest.news.limit(5)
    @query = Media.construct_query(:media_type=>'photos',:owner_id=>@activity_category.id,:owner_type=>'activity',:page=>1)
  end
  
end

app/controllers/admin/activity_categories_controller.rb
class Admin::ActivityCategoriesController < Admin::AdminController
  before_filter :handle_media_list, :only=>[:create,:update]
  cache_sweeper :activity_category_sweeper, :only=>[:create, :update, :destroy]
  
  def index
    @activity_categories = ActivityCategory.latest
  end

  def show
    @activity_category = ActivityCategory.find(params[:id])
  end

  def new
    @activity_category = ActivityCategory.new
  end

  def edit
    @activity_category = ActivityCategory.find(params[:id])
  end

  def create
    @activity_category = ActivityCategory.new(params[:activity_category])
    
    if @activity_category.save
      @activity_category.move_to_top
      redirect_to(admin_activity_categories_path, :notice => t("messages.saved", :name => t("activity_category.activity_category")))
    else
      render :action => "new"
    end
  end
  
  def update
    @activity_category = ActivityCategory.find(params[:id])
    if @activity_category.update_attributes(params[:activity_category])
      redirect_to(admin_activity_categories_path, :notice => t("messages.saved", :name => t("activity_category.activity_category")))
    else
      render :action => "edit"
    end
  end

  def destroy
    @activity_category = ActivityCategory.find(params[:id])
    authorize! :destroy, @activity_category
    @activity_category.destroy
    
    redirect_to(admin_activity_categories_url, :notice => t("messages.deleted"))
  end
  
  def update_order
    moved_category = ActivityCategory.find(params[:id])
    if params[:prev_id]!= "-1"
      previous_category = ActivityCategory.find(params[:prev_id])
      moved_category.remove_from_list
      moved_category.insert_at(previous_category.position + 1)
    else
      moved_category.move_to_top
    end
    
    render :nothing => true
  end
  
  #######
  private
  #######
  
  def handle_media_list
    begin
      if(params[:activity_category][:media])
        media_list = ActiveSupport::JSON.decode(params[:activity_category][:media])
        media_list = media_list.collect{|m| Media.find_or_create(m['id'] , m['mediaType'], m['thumbnail'])}
        params[:activity_category][:media] = media_list
      end
    rescue
    end
  end
end

app/helpers/activity_categories_helper.rb
module ActivityCategoriesHelper
end

app/views/admin/activity_categories/_form.html.erb
<%= form_for(@activity_category, :url=>@activity_category.id ? admin_activity_category_path(@activity_category) : admin_activity_categories_path) do |f| %>
  <div class="grid_16">
    <%= render :partial=>'shared/form_errors', :locals=>{:obj=>@activity_category} %>
    <div class="box">
      <h2><%= form_title%></h2>
      <div class="block">
          <div class="page_actions">
            <%= f.label :name %>
            <%= f.text_field :name %>              
          </div>
          <div class="page_actions">
            <%= f.label :description %>
            <%= f.text_area :description, :class=>"tinymce" %>             
          </div>
          <div class="page_actions">
            <%= f.label :short_description %>
            <%= f.text_area :short_description, :rows => 5 %>           
          </div>
          <div class="page_actions">
            <%= f.label :donatable %>
            <%= f.check_box :donatable %>           
          </div>
          <%= render :partial=> 'admin/shared/media_picker', :locals=>{:association => :media, :parent=>@activity_category, :f=> f } %>
          <p class="controls">
            <%= f.submit "حفظ النشاط الخيرى", :class=>"button" %> <%= link_to "إلغاء", admin_activity_categories_path %>
          </p>
      </div>
    </div>
  </div>
<% end %>
<%= render 'shared/tinymce' %>

app/views/admin/activity_categories/edit.html.erb
<div class="grid_16">
  <h2 id="page-heading"></h2>
</div>

<%= render :partial=>'form', :locals=>{:form_title=>"تعديل النشاط الخيرى"} %>

app/views/admin/activity_categories/index.html.erb
<div class="grid_16">
  <h2 id="page-heading">الأنشطة الخيرية</h2>
</div>

<div class="grid_16">
  <%= link_to "إضافة نشاط خيرى جديد", new_admin_activity_category_path, :class=>"add_btn"%> 
  <table>
    <caption></caption>
    <colgroup>
      <col class="colA">
      <col class="colB">
      <col class="colC">
    </colgroup>
    <thead>
      <tr>
        <th class="table-head" colspan="3">قائمة الأنشطة</th>
      </tr>
      <tr>
        <th>النشاط الخيرى</th>
        <th>الوصف</th>
        <th class="currency"></th>
      </tr>
    </thead>                      
    <tbody>
      <% @activity_categories.each do |activity_category| %>
      <tr class="<%= cycle('odd', 'even')%>" ac_id="<%= activity_category.id %>" id="activity_category_<%= activity_category.id %>">
        <th class="list_item_name" >
          <h5><%= activity_category.name %></h5>
        </th>
        <td class="list_item_descreption">
          <p><%= activity_category.description ? activity_category.description.html_safe : ""%></p>
        </td>                 
        <td  class="list-item-actions"> 
          <%= link_to 'تعديل', edit_admin_activity_category_path(activity_category), :class=>"edit", :title=> "تعديل"%>
          <% if can? :destroy, activity_category %>
          <%= link_to 'حذف', admin_activity_category_path(activity_category), :class=>"delete", :confirm => 'هل انت متأكد من حذف هذا النشاط الخيرى ?', :method => :delete , :title=>"حذف"%>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>   

<% content_for :javascripts do %>
<script>
  $("tbody").sortable({
    axis: 'y',
    cursor: 'crosshair',
    distance: 20,
    zIndex: 5,
    revert: true,
    stop: function(event, ui){
      var moved_id = ui.item.attr("ac_id")
      if ($("#activity_category_" + moved_id).prev().attr("ac_id")) {
        var prev_id = $("#activity_category_" + moved_id).prev().attr("ac_id")
      }else{
        var prev_id = -1
      } 
      
      $.ajax({
        url: "/admin/activity_categories/update_order/" + moved_id + "/" + prev_id,
        type: "POST",
        statusCode: {
          200: function(){
          },
          404: function(){
             $("tbody").sortable('cancel');
          },
          500: function(){
             $("tbody").sortable('cancel');
          },
        }
      });
    }
  });
</script>
<% end %>

app/views/admin/activity_categories/new.html.erb
<div class="grid_16">
  <h2 id="page-heading"></h2>
</div>

<%= render :partial=>'form', :locals=>{:form_title=>"إضافة نشاط خيرى جديد"} %>