config/routes.rb
Resala::Application.routes.draw do  
  resources :sessions, :only => [:new]
  resources :testimonials, :branches, :only => [:index, :show]
  resources :newsletter_subscribers, :only => [:create]
  resources :donation_requests, :feedbacks, :only => [:new, :create]
  resources :pages, :only => [:show, :user_info]
  resources :questions, :only => :index
  resources :activity_categories, :only => [:index,:show] do
    resources :questions, :only => :index
  end
  resources :activities, :only => [:show, :new, :create, :index]  do
    resources :achievements, :only => [:new, :create] 
    member do
      post :notify_comment
      get :join_activity
      post :quit
      get :volunteers
    end
  end
  resources :donations, :only=>[:new,:create,:index] do
    collection do
      get :handle_response
    end 
  end
  resources :news, :stories, :only => [:index, :show]  do
    collection do
      get 'search'
    end
  end
  resources :volunteers, :only => [:new, :create, :index, :show, :edit, :update] do 
    collection do
      post 'activities_authority'
      get 'request_activities_authority'
      get 'gateway'
    end
    member do
      get 'activities'
      get 'dashboard'
      get 'previous_activities'
      get 'upcoming_activities'
      get 'volunteer_details'
      post 'update_join_activity'
    end
    resources :activities, :only => []  do
      resources :achievements, :only => [:new, :create, :show] 
      member do
        get :volunteers
    	post :request_close
      	get :preview
      end
    end
  end
  
  namespace :admin do
    resources :activity_categories, :branches, :testimonials, :articles, :newsletter_subscribers, :achievements_types
    resources :donation_requests, :only => [:index, :show, :destroy, :update]
    resources :donations, :only => [:index]
    resources :activities, :only => [:index,:show,:update] do
      member do
        put 'publish'
        put 'announce'
        put 'reject'
        get 'members'
        put 'close'
      end
      collection do
        get 'email_counts'
      end
    end
    resources :volunteers, :only => [:index, :show, :edit, :update, :destroy] do 
      member do
        get 'authority_volunteer_details'
        post 'update_activities_authority_status'
      end
    end
    resources :admins, :only => [:index] do 
      member do
        post 'activate'
      end
    end
    resources :reports, :only=>[] do
      collection do
        get 'volunteers'
        get 'donations'
        get 'donation_requests'
      end
    end
    resources :questions, :except => [:show]
    match '/broadcast_email' => 'emails#new',    :as=>'new_bulk_email' , :via => :get
    match '/broadcast_email' => 'emails#create', :as=>'send_bulk_email', :via => :post
    match '/email_counts' => 'emails#email_counts', :as=>'email_counts', :via => :post
    match '/broadcast_email/preview' => 'emails#preview', :as=>'email_preview', :via=> :post
    match '/activity_categories/update_order/:id/:prev_id' => 'activity_categories#update_order', :as => :update_order, :via => :post
  end
  
  get "media/index"
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider/callback' => 'sessions#create'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/admin_login/:provider' => 'sessions#admin_login', :as => :admin_login
  match '/login/:provider' => 'sessions#login', :as => :login
  match '/volunteering/:provider' => 'sessions#volunteering', :as => :volunteering
  match '/media(/:media_type)(/pages/:page)(.:format)' => 'media#index', :as=> 'media'
  match '/media/albums/:album_id/:media_type(/pages/:page)(.:format)' => 'media#index', :as=> 'album_photos'
  match '/media/:media_type/:fb_id(.:format)' => 'media#show', :as=> 'media_show'
  match '/admin' => 'admin/articles#index'
  match 'home' => 'pages#show', :id => :home
  match 'user_info' => 'pages#user_info'
  match '/volunteers/:id/activities/:activity_id' => 'volunteers#activity', :via => :get, :as=> 'volunteer_activity'
  match '/volunteers/:id/activities/:activity_id/edit' => 'activities#edit', :as=> 'edit_volunteer_activity'
  match '/volunteers/:id/activities/:activity_id' => 'activities#update', :via => :put, :as=> 'update_volunteer_activity'
  match '/subscribe_confirmation/:token' => 'newsletter_subscribers#subscribe_confirmation', :as=> 'subscribe_confirmation'
  match '/unsubscribe' => 'newsletter_subscribers#unsubscribe', :as=> 'unsubscribe'
  match '/unsubscribe_confirmation/:token' => 'newsletter_subscribers#unsubscribe_confirmation', :as=> 'unsubscribe_confirmation'
  match '/Adm!nD@ta$3cuReP@ge' => 'pages#admin_data_entry', :via=> :get, :as=> 'admin_data_entry'
  match '/update_admin_data' => 'pages#update_admin_data', :via=> :put
  root :to => 'pages#show', :id => :home
  

end

app/views/shared/_activity_categories.html.erb
<div class="side_element">
  <h2 class="hideText related_activites_block">الأنشطة المتعلقة</h2>
  <p class="related_activities">
    <% activity_categories.each do |activity_category|%>
      <%= link_to activity_category.name, activity_category %>
    <% end %>
  </p>
</div>

app/views/shared/_branches.html.erb
<div class="side_element">
  <h2 class="hideText related_branches_block">الفروع المتعلقة</h2>
  <% branches.each do |branch|%>
    <%= link_to branch.name, branch, :class=>"branch_tage" %>
  <% end %>
</div>

app/views/shared/_cookies_messages.html.erb
<div id="flash_notice" class="flash-notice" style="display: none;"><h4></h4></div>
<div id="flash_alert" class="alert" style="display: none;"></div>

<% content_for :javascripts  do %>
<script>
  showFlashMessages();
</script>
<% end %>

app/views/shared/_email_counts.html.erb
<div> سيتم إرسال <%= count %> رسالة إلكترونية لإخطار المتطوعين </div>

app/views/shared/_facebook_like_box.html.erb
<div class="side_element">
<div id="fb-root"></div>
</div>
<fb:like-box href="http://www.facebook.com/Resala.org" width="292" show_faces="true" border_color="" stream="true" header="true"></fb:like-box>

app/views/shared/_form_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= t("messages.form_error") %></h2>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_pagination.html.erb
<script type="text/html" id="pagination-template">
  <![CDATA[
      <%% if(this.next != undefined || this.prev != undefined){%>
      <div id="pagination_links" class="pagination">
        <%% if(this.prev != undefined ){%>
        <a href="<%%= this.prev %>" rel="previous" class="previous_page" data-remote="true"><%=t('messages.prev')%></a>
        <%% }else{%>
        <span class="previous_page disabled"><%=t('messages.prev')%></span>
        <%% }%>
        
        <%% if(this.next != undefined ){%>
        <a href="<%%= this.next %>" rel="next" class="next_page" data-remote="true"><%=t('messages.next')%></a>
        <%% }else{%>
        <span class="next_page disabled"><%=t('messages.next')%></span>
        <%% }%>
      </div>
      <%% }%>
  ]]>
</script>

app/views/shared/_related_articles.html.erb
<div class="side_element">
  <h2 class="hideText <%= type == 'news' ? 'related_news_block' : 'related_stories_block' %>"><%= block_title %></h2>
  <ul class="recent">
    <% related_articles.each do |related_article| %>
    <li>
      <%= link_to related_article.title, url_for(:action=>:show, :controller=>type, :id=>related_article.id)%>
      <div class="article_activities">
        <div class="date">
          <span>كتبت في</span>
          <%= l( related_article.created_at.to_datetime, :format=>:styled).html_safe %>
        </div>
        <div class="comments">
          <span class="comment_no"><fb:comments-count href=<%= url_for(:action=>:show, :controller=>type, :id=>related_article.id, :only_path=>false) %>></fb:comments-count> تعليقات</span>
        </div>  
      </div>
    </li>
    <% end %>
  </ul>
  <% if show_more %>
    <%= link_to "المزيد", "/news?activity_category_id=#{activity_category_id}", :class=>"more hideText" %>
  <% end %>
</div>

app/views/shared/_select_all.html.erb
<%= link_to "اختر الكل", "#", :class=> select_all_class %>

<% content_for :javascripts do %>
<script>
  $(document).ready(function(){
    var selectAllClass = "<%= select_all_class %>"; 
    var inputsToCheck = "<%= inputs_to_check %>";
    var recount = <%= local_assigns[:recount] ? "true" : "false" %>;
    $('.' + selectAllClass ).toggle(function(){
      $('.' + inputsToCheck + ":enabled" ).attr("checked", true);
      if(recount){
        update_email_counts();
      }
      return false;
    }, function(){
      $('.' + inputsToCheck + ":enabled" ).attr("checked", false);
      if(recount){
        update_email_counts();
      }
      return false;
    });
  });
</script>
<% end %>

app/views/shared/_share_links.html.erb
<div class="addthis_toolbox addthis_default_style ">
  <div class="fb-like" data-href="<%=request.url%>" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
  <a class="addthis_button_preferred_1"></a>
  <a class="addthis_button_preferred_2"></a>
  <a class="addthis_button_preferred_3"></a>
  <a class="addthis_button_compact"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4deb3d8a2f9d22ba"></script>

app/views/shared/_side_ads.html.erb
<div class="side_element ads">
  <%= link_to image_tag("graphics_ar/volunteer_banner.png") , activities_path %>
</div>
<div class="side_element ads">
  <%= link_to image_tag("graphics_ar/donate.png") , page_path('how_to_donate') %>
</div>
<div class="side_element ads">
  <%= image_tag("dummy/ad.png")%>
</div>

app/views/shared/_start_now_activity.html.erb
<div class="side_element">
<h2 class="hideText strat_now">ابدأ الآن</h2>
<% if current_user %>
  <% if can?(:create, Activity.new)%>
    <%= link_to "تنظيم أعمال تطوعية", new_activity_path, :class=>"addActivity_req" %>
  <% elsif can?(:request_activities_authority, current_user) %>
    <%= link_to 'طلب إذن لتنظيم أعمال تطوعية', request_activities_authority_volunteers_path, :class=>"volunteer_req" %>
  <% else %>
    <div class="section_intro">              
      <p> طلبك لتنظيم أعمال تطوعية جديدة قيد المراجعة من الإدارة.</p>
    </div>
  <% end %>
<% else %>
  <%= link_to "إنشاء حساب متطوع", volunteering_path(:facebook), :class=>"registration_req register_button" %>
  <%= link_to "تسجيل الدخول", login_path(:facebook), :class=>"login_req login_button" %>
<% end %>
</div>

app/views/shared/_top_search_form.html.erb
<div class="search_box">
  <% form_tag "/news/search", :method => 'get', :id=>"top_search_form" do |form| %>
    <fieldset>
      <div class="search_item">
        <%= text_field_tag :keyword, params[:keyword], {:class=>"box_shadow"} %>
        <%= submit_tag "", :class=>"search_btn" %>
      </div>
      <div>
        <!-- <%= select_tag :type, options_for_select([["#.('1", "news"], ["B55 E$+1)", "stories"]]), :id=>"top_search_form_type" %> -->
      </div> 
    </fieldset>
  <% end %>
</div>
<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      search_words = "بحث في الأخبار .. ..";
      
      if($(".search_item #keyword").val().length == 0){
        $(".search_item #keyword").val(search_words);
      }
      $('.search_item #keyword').focusout(function () {
        if($(".search_item #keyword").val().length == 0){
          $(this).val(search_words);
        }
      });
      $('.search_item #keyword').focusin(function () {
        if($(".search_item #keyword").val() == search_words){
          $(this).val("");
        }
      });
    });
  </script>
<% end %>

app/views/shared/_user_info.html.erb
<% if current_user %>
<ul class="user_menu">
  <% if can? :show, Volunteer %>
  <li>
    <span>
      <span>أهلا &nbsp;</span><%= link_to current_user.name, volunteer_path(current_user), :title=>"اضغط لمشاهدة بياناتك" %>
      <% if can? :edit, current_user %>
      <%= link_to "- تعديل بياناتى", edit_volunteer_path(current_user), :title=>"تعديل بياناتى الشخصية" %>
      <% end %>
    </span>
  </li>
  <% else %>
  <li><span>أهلا <%= current_user.name %></span></li>
  <% end %>
  <li><%= link_to "خروج", logout_path, :class=>"logout" %></li>
</ul>
<% else %>
<ul class="user_menu">
  <li><span>يمكنك التطوع معنا</span></li>
  <li><%= link_to "تطوع", volunteering_path(:facebook), :class=>"register register_button" %></li>
  <li><%= link_to "دخول", login_path(:facebook), :class=>"login login_button" %></li>
</ul>
<% end %>